version: '3.7'
# Settings and configurations that are common for all containers

services:
    reverse-proxy-fiit-stu:
    # The official v2 Traefik docker image
      image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
      container_name: reverse-proxy-fiit-stu
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - --providers.docker.network=traefik-fiit-stu
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
        - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
        - "--entrypoints.web.http.redirections.entryPoint.priority=10" # disable permanent forwarding for every route
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # <== Enable TLS-ALPN-01 to generate and renew ACME certs
        - "--certificatesresolvers.myresolver.acme.email=${useremail}"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      ports:
        # The HTTP port
        - "80:80"
        # The HTTPS port
        - "443:443"
        # The Web UI (enabled by --api.insecure=true)
        - "8089:8080"
      volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
        # volume to store letsencrypt certificates
        - "./letsencrypt:/letsencrypt"
      networks:
        - traefik-fiit-stu


    postgres-fiit-stu:
      networks:
        - traefik-fiit-stu
      container_name: postgres-fiit-stu
      ports:
        - "5433:5432"
      image: postgres:10.13
      restart: unless-stopped

      environment:
        - "LC_ALL=C.UTF-8"
        - "POSTGRES_DB"
        - "POSTGRES_USER"
        - "POSTGRES_PASSWORD"
        - "POSTGRES_PORT"
      volumes:
        - ${LOCAL_STORAGE}/database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
        - ./triggers:/triggers

    solr-fiit-stu:
      networks:
        - traefik-fiit-stu
      image: coronawhy/solr:8.9.0
      container_name: solr-fiit-stu
      privileged: true
      ports:
        - "8983:8983"
      environment:
        - "SOLR_HOST=solr-fiit-stu"
        - "SOLR_PORT=8983"
        - "SOLR_JAVA_MEM=-Xms1g -Xmx1g"
        - "SOLR_OPTS=-Dlog4j2.formatMsgNoLookups=true"
      volumes:
        - solr-data:/opt/solr/server/solr/collection1/data
        - ./config/schema.xml:/var/solr/data/collection1/conf/schema.xml
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.solr.rule=Host(`solr.${traefikhost}`)"
        - "traefik.http.services.solr.loadbalancer.server.port=8983"
        - "traefik.http.routers.solr.tls=true"
        - "traefik.http.routers.solr.tls.certresolver=myresolver"   
    
    dataverse-fiit-stu:
      networks:
        - traefik-fiit-stu
      image: ${DOCKER_HUB}:${VERSION}
      container_name: dataverse-fiit-stu
      privileged: true
      user:
        "root"
      ports:
        #- "443:443"
        - "4848:4848"
        - "8080:8080"
      environment:
        - "CVM_SERVER_NAME=CESSDA" #Optional
        - "WEBHOOK"
        - "CESSDA"
        - "CLARIN"
        - "doi_authority"
        - "doi_provider"
        - "doi_username"
        - "doi_password"
        - "dataciterestapiurlstring"
        - "baseurlstring"
        - "aws_bucket_name"
        - "aws_s3_profile"
        - "aws_endpoint_url"
        - "system_email"
        - "mailhost"
        - "mailuser"
        - "no_reply_email"
        - "smtp_password"
        - "smtp_port"
        - "socket_port"
        - "federated_json_file"
        - "bucketname_1"
        - "minio_label_1"
        - "minio_bucket_1"
        - "bucketname_2"
        - "minio_profile_1"
        - "minio_label_2"
        - "minio_bucket_2"
        - "minio_profile_2"
        - "DATAVERSE_DB_HOST"
        - "DATAVERSE_DB_USER"
        - "DATAVERSE_DB_PASSWORD"
        - "DATAVERSE_DB_NAME"
        - "DATAVERSE_SERVICE_HOST"
        - "DATAVERSE_URL"
        - "SOLR_SERVICE_HOST"
        - "SOLR_SERVICE_PORT"
        - "CVM_SERVER_URL=https://ns.${traefikhost}"
        - "LANG=en"
        - "cvManager=http://"
        - "BUNDLEPROPERTIES=Bundle.properties"
        - "ADMIN_EMAIL=admin@localhost"
        - "MAIL_SERVER=mailrelay"
        - "SOLR_LOCATION=solr-fiit-stu:8983"
        - "INIT_SCRIPTS_FOLDER"
        - "hostname"
        - "MAINLANG"
        - "POSTGRES_SERVER"
        - "POSTGRES_PORT"
        - "POSTGRES_DATABASE"
        - "POSTGRES_USER"
        - "POSTGRES_PASSWORD"
        - "PGPASSWORD=dvnsecret"
        - "TWORAVENS_LOCATION=NOT INSTALLED"
        - "RSERVE_HOST=localhost"
        - "RSERVE_PORT=6311"
        - "RSERVE_USER=rserve"
        - "RSERVE_PASSWORD=rserve"
        - "JVM_OPTS='-Xmx1g -Xms1g -XX:MaxPermSize=2g -XX:PermSize=2g'"
      depends_on:
        - postgres-fiit-stu
        - solr-fiit-stu
      volumes:
        - ${CONFIGURATION_PATH}/secrets:/secrets
        - ${LOCAL_STORAGE}/data:/data
        - ${DOCROOT}/docroot:/opt/docroot
        - ./init.d:/opt/payara/init.d
        - ./triggers:/opt/payara/triggers
        - ./config/schema.xml:/opt/payara/dvinstall/schema.xml
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dataverse.rule=Host(`www.${traefikhost}`)"
        - "traefik.http.services.dataverse.loadbalancer.server.port=8080"
        - "traefik.http.routers.dataverse.tls=true"
        - "traefik.http.routers.dataverse.tls.certresolver=myresolver"  
volumes:
  database-data:
  solr-data:
  dataverse-data:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

networks:
  traefik-fiit-stu:
    external: true
